### ISSUE TITLE
1.7.10 Build Script Issues.

### ISSUE THREAD

**Issue by StoneLegion** [Team-RTG/Realistic-Terrain-Generation#1344]
I know that 1.7.10 not being worked on I was hoping I could get help fixing a Build error so I can go ahead and fix a few little things or attempt to by learning and exploring. I played with quite a few 1.7.10 Open Source Mods but yours is a bit diff it had some build issues on top of another issue. I was hoping if someone had time they might be able to clean it up if possible.

Thanks.

I'm trying to enable Lava Lakes on the 1.7.10 Version in BoP Biomes / Vanilla Biomes.. I fixed the build.gradle and a slight fix in the build.prop both version stuff I guess they changed or maybe error. 

Anyways it compiles fine up to ApiJava and on Both Windows and Linux I seem to get jammed up on this error:

```
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/s1/gitstuff/Realistic-Terrain-Generation/src/api/java/enhancedbiomes/helpers/ColorizerFoliageBirch.java:10: error: cannot find symbol
    {
    ^
  symbol:   constructor ColorizerFoliage()
  location: class ColorizerFoliage
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
1 warning
:compileApiJava FAILED

FAILURE: Build failed with an exception.
```

Any help would be great once again I know that no one is working on the 1.7.10 version but it be nice if we could fix the builder so others can improve on it if possible.

Thanks.

**Comment by srs-bsns** [comment]
...

**Comment by StoneLegion** [comment]
How I open this again. Someone can't even keep build scripts working needs a good old beating ;)

**Comment by srs-bsns** [comment]
1.7.10 is dead and has been for a long time. Even 1.12 is dead now.
No one is going to give you support for this. This is like asking Microsoft for support with Windows 95.
